using System;

namespace Existence.Earth.Countries.UnitedStates
{
    public class USCityAttribute : Attribute
    {
        public USCities City { get; set; }
        public USCityAttribute(USCities City)
        {
            this.City = City;
        }
    }

    public class USCitiesAttribute : Attribute
    {
        public USCities[] Cities { get; set; }
        public USCitiesAttribute(params USCities[] Cities)
        {
            this.Cities = Cities;
        }
    }

    public enum USCities
    {
        AlabamaBirmingham,
        AlabamaMobile,
        AlabamaMontgomery,
        AlaskaAnchorage,
        AlaskaJuneau,
        AmericanSamoaPagoPago,
        ArizonaPhoenix,
        ArkansasFortSmith,
        ArkansasLittleRock,
        CaliforniaLosAngeles,
        CaliforniaPasadena,
        CaliforniaSacramento,
        CaliforniaSanDiego,
        CaliforniaSanFrancisco,
        ColoradoDenver,
        ConnecticutHartford,
        ConnecticutNewHaven,
        DelawareDover,
        DelawareWilmington,
        FloridaMiami,
        FloridaOrlando,
        FloridaTallahassee,
        GeorgiaAtlanta,
        GeorgiaMacon,
        GeorgiaSavannah,
        GuamHagåtña,
        HawaiiHonolulu,
        IdahoBoise,
        IllinoisChicago,
        IllinoisEastSaintLouis,
        IllinoisSpringfield,
        IndianaIndianapolis,
        IndianaSouthBend,
        IowaCedarRapids,
        IowaDesMoines,
        KansasTopeka,
        KentuckyFrankfort,
        KentuckyLexington,
        KentuckyLouisville,
        LouisianaBatonRouge,
        LouisianaNewOrleans,
        LouisianaShreveport,
        MaineAugusta,
        MainePortland,
        MarylandAnnapolis,
        MarylandBaltimore,
        MassachusettsBoston,
        MichiganDetroit,
        MichiganGrandRapids,
        MichiganLansing,
        MinnesotaSaintPaul,
        MississippiJackson,
        MississippiOxford,
        MissouriJeffersonCity,
        MissouriKansasCity,
        MissouriSaintLouis,
        MontanaBillings,
        MontanaHelena,
        NebraskaLincoln,
        NebraskaOmaha,
        NevadaCarsonCity,
        NevadaLasVegas,
        NewHampshireConcord,
        NewJerseyNewark,
        NewJerseyTrenton,
        NewMexicoAlbuquerque,
        NewMexicoSantaFe,
        NewYorkAlbany,
        NewYorkBrooklyn,
        NewYorkBuffalo,
        NewYorkNewYorkCity,
        NewYorkSyracuse,
        NorthCarolinaCharlotte,
        NorthCarolinaGreensboro,
        NorthCarolinaRaleigh,
        NorthDakotaBismarck,
        NorthernMarianaIslandsSaipan,
        OhioCincinnati,
        OhioCleveland,
        OhioColumbus,
        OklahomaMuskogee,
        OklahomaOklahomaCity,
        OklahomaTulsa,
        OregonPortland,
        OregonSalem,
        PennsylvaniaHarrisburg,
        PennsylvaniaPhiladelphia,
        PennsylvaniaPittsburgh,
        PennsylvaniaScranton,
        PuertoRicoSanJuan,
        RhodeIslandProvidence,
        SouthCarolinaColumbia,
        SouthDakotaPierre,
        SouthDakotaSiouxFalls,
        TexasAustin,
        TexasDallas,
        TexasHouston,
        TexasSanAntonio,
        TexasTyler,
        TennesseeKnoxville,
        TennesseeMemphis,
        TennesseeNashville,
        UtahSaltLakeCity,
        VermontBurlington,
        VermontMontpelier,
        VirginiaRichmond,
        VirginiaRoanoke,
        UnitedStatesVirginIslandsCharlotteAmalie,
        UnitedStatesVirginIslandsSaintThomas,
        UnitedStatesVirginIslandsSaintCroix,
        WashingtonDistrictOfColumbia,
        WashingtonOlympia,
        WashingtonSeattle,
        WashingtonSpokane,
        WestVirginiaCharleston,
        WestVirginiaWheeling,
        WisconsinMadison,
        WisconsinMilwaukee,
        WyomingCheyenne,
    }
}
